module.exports = {
  ROLES:{
    ADMIN: "ADMIN",
    MEMBER: "MEMBER",
    SUPER_ADMIN: "SUPER_ADMIN",
    OWNER: "OWNER",
    ANALYST: "ANALYST"
  },
  PACKAGES:{
    FREE_TRIAL: "FREE TRIAL",
    STANDARD: "STANDARD",
    UNLIMITED: "UNLIMITED"
  },
  CHECK:{
    MEMBER: "MEMBER",
    SURVEY: "SURVEY",
    PROJECT: "PROJECT"
  },
  PLATFORMS:[
    "SEBSIB_OFFICE_1",
    "SEBSIB_COLLECT_2",
    "SEBSIB_ADMIN_3"
  ]
}